### ISSUE TITLE
[SUGGESTION] Config option to blanket halt spawns of all mobs in specific biomes

### ISSUE THREAD

**Issue by Sunconure11** [b3spectacled/custom-spawns#10]
Just as the title implies. We don’t seem to have an option for such anyways, unless I missed something

**Comment by b3spectacled** [comment]
If you are on 1.19.3, the latest version of the mod adds support for using biome tags instead of biome IDs for specifying mob additions, removals, and modifications.

**Comment by Sunconure11** [comment]
Stuck on 1.19.2 unfortunately, due to the decisions of some mod devs.
