### ISSUE TITLE
[1.16.5] Mob removals feature doesn't work

### ISSUE THREAD

**Issue by ByPaco10** [b3spectacled/custom-spawns#12]
Should be straightforward,
crash report: https://pastebin.com/chY5PSxf

**Comment by b3spectacled** [comment]
Apologies, I'll get on this.

EDIT: Could you please try deleting the config and regenerating it to see if that has any effect? There may be issues if the old config for the previous problematic version is still present. If that still doesn't work, please share the non-working config file.

**Comment by ByPaco10** [comment]
For some reason deleting the config file didn't work, but deleting the entire .minecraft folder worked, probably because one of my performance mods, anyway, it works now, it was a problem on my end, thanks anyway ^^, you are the first modder to actually fix a critical error in fabric 1.16.5
