### ISSUE TITLE
Not enough documentation?

### ISSUE THREAD

**Issue by MechanosG** [b3spectacled/custom-spawns#13]
While I'm sure this mod helps a seasoned modder..  how is your average joe supposed to figure out how to use it?

For example, say I want to make Skeletons stop spawning completely.
```
Mob Spawn Removals

    biomeId: Fully-qualifed biome Identifier.
    mobId: Fully-qualified mob Identifier.
```
Does this mean I have to add every single "biome identifier", just to make Skeletons stop spawning?  How would one find out every single identifier?  How does one find mob identifiers?  Is there wildcards?  Can I just slap a * in there, and have all biomes be recognized?

I really wish this mod had a "for Dummies" section.  *~nervous awkward laugh*

**Comment by purejosh** [comment]
You're completely right. There's not enough documentation for this.

**Comment by b3spectacled** [comment]
I've updated the repository with a wiki, the relevant sections also include examples: https://github.com/b3spectacled/custom-spawns/wiki

Please open a new issue if you still have questions.

**Comment by purejosh** [comment]
Thank you for the updates! Very much appreciated.

**Comment by b3spectacled** [comment]
No problem, I've expanded the documentation a tad bit more to better explain the format of the biome/mob/tag IDs.
