### ISSUE TITLE
Allow blocking mob spawns from every biome instead of blocking per mob per biome

### ISSUE THREAD

**Issue by ninjakitty844** [b3spectacled/custom-spawns#15]
You can only block 1 mob from 1 biome per 1 rule. This is very inefficient. I think it would be better to aim towards a system like what the Mob Filter mod (for Fabric 1.19.3) has. That mod allows you to block infinite number of mobs from infinite number of biomes per 1 rule. Each rule would just be you specifying the set of conditions required to block a mob spawn. For example, one rule could be block a spawn if the entity is a creeper or bat (if no biome specified then its every biome by default)

**Comment by b3spectacled** [comment]
Hi there, agree completely. I've added support for using biome tags instead individual biome ids for mob additions, removals, and modifications. Please see version 0.8+1.19.3.
