### ISSUE TITLE
Crash on startup on dedicated server [1.16.5]

### ISSUE THREAD

**Issue by ByPaco10** [b3spectacled/custom-spawns#7]
crash: **net.fabricmc.loader**.impl.FormattedException: java.lang.AssertionError: java.lang.**NoSuchFieldException: MONSTER**

Fabric Loader 0.13.1 -> (probably loader related) (now tested with fabric loader from 0.13 to 0.14.6, no loader works)
Fabric API (CUSTOM) 0.42.0+Artysen -> (custom api not related to crash)

Entire crash: https://pastebin.com/PTFgGsqv

Modlist: https://pastebin.com/u4cR5QUJ

**Comment by b3spectacled** [comment]
Should be fixed with 0.6.1+1.16.5, please take a look.

**Comment by ByPaco10** [comment]
Amazing work! Works flawlessly

**Comment by ByPaco10** [comment]
Well, at least until you don't configure mob removals, but thats a different issue, i'll open another one
